import { createContext, useContext, useMemo, useState, type ReactNode } from 'react';

export type CountryCode = 'hu' | 'de' | 'es' | 'fr' | 'us' | 'fi' | 'nl';

interface CountryConfig {
  code: CountryCode;
  label: string;
  locale: string;
  globeCountry: string;
  accentHex: string;
  accentHoverHex: string;
  accentRgb: string;
  accentHsl: string;
  borderHsl: string;
  inputHsl: string;
  countryName: string;
  countryNameUpper: string;
}

const COUNTRY_CONFIGS: Record<CountryCode, CountryConfig> = {
  hu: {
    code: 'hu',
    label: 'Magyarország',
    locale: 'hu-HU',
    globeCountry: 'Hungary',
    accentHex: '#C8243C',
    accentHoverHex: '#A01E30',
    accentRgb: '200, 36, 60',
    accentHsl: '352 68% 46%',
    borderHsl: '352 46% 24%',
    inputHsl: '352 28% 18%',
    countryName: 'Magyarország',
    countryNameUpper: 'MAGYARORSZÁG',
  },
  de: {
    code: 'de',
    label: 'Németország',
    locale: 'de-DE',
    globeCountry: 'Germany',
    accentHex: '#111827',
    accentHoverHex: '#1f2937',
    accentRgb: '17, 24, 39',
    accentHsl: '220 39% 11%',
    borderHsl: '220 25% 24%',
    inputHsl: '220 18% 18%',
    countryName: 'Deutschland',
    countryNameUpper: 'DEUTSCHLAND',
  },
  es: {
    code: 'es',
    label: 'Spanyolország',
    locale: 'es-ES',
    globeCountry: 'Spain',
    accentHex: '#F59E0B',
    accentHoverHex: '#D97706',
    accentRgb: '245, 158, 11',
    accentHsl: '38 92% 50%',
    borderHsl: '38 58% 26%',
    inputHsl: '38 28% 18%',
    countryName: 'España',
    countryNameUpper: 'ESPAÑA',
  },
  fr: {
    code: 'fr',
    label: 'Franciaország',
    locale: 'fr-FR',
    globeCountry: 'France',
    accentHex: '#2563EB',
    accentHoverHex: '#1D4ED8',
    accentRgb: '37, 99, 235',
    accentHsl: '221 83% 53%',
    borderHsl: '221 42% 24%',
    inputHsl: '221 22% 18%',
    countryName: 'France',
    countryNameUpper: 'FRANCE',
  },
  us: {
    code: 'us',
    label: 'USA',
    locale: 'en-US',
    globeCountry: 'United States of America',
    accentHex: '#1D4ED8',
    accentHoverHex: '#1E40AF',
    accentRgb: '29, 78, 216',
    accentHsl: '221 75% 48%',
    borderHsl: '221 38% 24%',
    inputHsl: '221 20% 18%',
    countryName: 'United States',
    countryNameUpper: 'UNITED STATES',
  },
  fi: {
    code: 'fi',
    label: 'Finnország',
    locale: 'fi-FI',
    globeCountry: 'Finland',
    accentHex: '#0EA5E9',
    accentHoverHex: '#0284C7',
    accentRgb: '14, 165, 233',
    accentHsl: '199 89% 48%',
    borderHsl: '199 42% 24%',
    inputHsl: '199 22% 18%',
    countryName: 'Suomi',
    countryNameUpper: 'SUOMI',
  },
  nl: {
    code: 'nl',
    label: 'Netherlands',
    locale: 'nl-NL',
    globeCountry: 'Netherlands',
    accentHex: '#F97316',
    accentHoverHex: '#EA580C',
    accentRgb: '249, 115, 22',
    accentHsl: '25 95% 53%',
    borderHsl: '25 48% 24%',
    inputHsl: '25 22% 18%',
    countryName: 'Nederland',
    countryNameUpper: 'NEDERLAND',
  },
};

const UI_TRANSLATIONS = {
  hu: {
    'nav.globe': 'ÁTTEKINTÉS',
    'nav.markets': 'PIACOK',
    'nav.reality': 'VALÓSÁG ELLENŐR',
    'ticker.latest': 'Friss hírek',
    'export.pdf': 'Export PDF',
    'export.country': 'Ország',
    'stats.conflicts': 'KONFLIKTUSOK',
    'stats.highRisk': 'MAGAS KOCKÁZAT',
    'stats.articles': 'CIKKEK',
    'stats.sentiment': 'ÁTL. HANGULAT',
    'stats.countryImpact': '{country} HATÁS',
    'news.feed': 'Hírfolyam',
    'news.search': 'Kulcsszó keresése',
    'news.loading': 'Betöltés',
    'news.impactBadge': '{country} hatás',
    'news.impactTitle': 'Hatás {country}ra',
    'news.noResults': 'Nincs találat a megadott kulcsszóra.',
    'news.chat': 'Hírelemző',
    'news.original': 'Eredeti cikk megnyitása',
    'news.chatTitle': 'Hírelemző chat',
    'news.selected': 'Kiválasztott hír',
    'news.summary': 'Összefoglaló',
    'news.summaryMissing': 'Ehhez a cikkhez még nincs mentett összefoglaló.',
    'news.topics': 'Témák',
    'news.draft': 'Írd ide a kérdést...',
    'news.analyzing': 'Elemzem ezt a hírt...',
    'news.intro': 'Kérdezz bármit erről a hírről: "{title}".',
    'conflicts.activeZones': 'Aktív Konfliktuszónák',
    'conflicts.hotNow': 'Mi Forr Most',
    'conflicts.window': 'Utolsó 72 óra',
    'conflicts.description': 'Rangsorolt, friss konfliktuszóna-lista. A pontszám a frissességet és a konfliktusos hírjelek erősségét sűríti egybe.',
    'conflicts.high': 'Súlyos',
    'conflicts.medium': 'Feszült',
    'conflicts.low': 'Figyelendő',
    'conflicts.rising': 'Emelkedik',
    'conflicts.cooling': 'Lassul',
    'conflicts.stable': 'Stabil',
    'conflicts.score': 'Pontszám',
    'conflicts.updated': 'Frissítve',
    'conflicts.newsSignal': 'hírjel',
    'conflicts.articles': 'Cikkek',
    'conflicts.victims': 'Áldozat',
    'conflicts.empty': 'Jelenleg nincs elég erős, friss konfliktusjel ahhoz, hogy aktív zónaként megjelenjen.',
    'reality.header': 'Valóság Ellenőr',
    'reality.description': 'Illessz be egy cikklinket, és a panel megmutatja az ítéletet, a forrásminőséget, a pszichológiai eszközöket és a narratívakontextust.',
    'reality.input': 'Cikklink',
    'reality.placeholder': 'Illessz be egy cikklinket az elemzéshez',
    'reality.open': 'Elemzés megnyitása',
    'reality.unavailable': 'Ehhez az URL-hez jelenleg nem érhető el elemzés.',
    'reality.tryAnother': 'Próbálj ki egy másik linket, vagy nyisd meg az alábbi cikkek egyikét.',
  },
  de: {
    'nav.globe': 'ÜBERBLICK',
    'nav.markets': 'MÄRKTE',
    'nav.reality': 'REALITÄTSPRÜFER',
    'ticker.latest': 'Aktuelle Nachrichten',
    'export.pdf': 'PDF exportieren',
    'export.country': 'Land',
    'stats.conflicts': 'KONFLIKTE',
    'stats.highRisk': 'HOHES RISIKO',
    'stats.articles': 'ARTIKEL',
    'stats.sentiment': 'DURCHSCHN. STIMMUNG',
    'stats.countryImpact': '{country} AUSWIRKUNG',
    'news.feed': 'Nachrichtenstrom',
    'news.search': 'Nach Stichwort suchen',
    'news.loading': 'Wird geladen',
    'news.impactBadge': '{country}-Auswirkung',
    'news.impactTitle': 'Auswirkung auf {country}',
    'news.noResults': 'Keine Treffer für das eingegebene Stichwort.',
    'news.chat': 'News-Analyse',
    'news.original': 'Originalartikel öffnen',
    'news.chatTitle': 'News-Analyse-Chat',
    'news.selected': 'Ausgewählte Nachricht',
    'news.summary': 'Zusammenfassung',
    'news.summaryMissing': 'Für diesen Artikel gibt es noch keine gespeicherte Zusammenfassung.',
    'news.topics': 'Themen',
    'news.draft': 'Schreibe hier deine Frage...',
    'news.analyzing': 'Ich analysiere diese Nachricht...',
    'news.intro': 'Frag alles zu dieser Nachricht: "{title}".',
    'conflicts.activeZones': 'Aktive Konfliktzonen',
    'conflicts.hotNow': 'Was jetzt eskaliert',
    'conflicts.window': 'Letzte 72 Stunden',
    'conflicts.description': 'Gerankte Liste frischer Konfliktzonen. Die Punktzahl bündelt Aktualität und Stärke der Konfliktsignale.',
    'conflicts.high': 'Schwer',
    'conflicts.medium': 'Angespannt',
    'conflicts.low': 'Beobachten',
    'conflicts.rising': 'Steigend',
    'conflicts.cooling': 'Abkühlend',
    'conflicts.stable': 'Stabil',
    'conflicts.score': 'Punktzahl',
    'conflicts.updated': 'Aktualisiert',
    'conflicts.newsSignal': 'Signal',
    'conflicts.articles': 'Artikel',
    'conflicts.victims': 'Opfer',
    'conflicts.empty': 'Derzeit gibt es nicht genug starke, frische Konfliktsignale für eine aktive Zone.',
    'reality.header': 'Realitätsprüfer',
    'reality.description': 'Füge einen Artikellink ein, und das Panel zeigt Urteil, Quellenqualität, psychologische Mittel und Narrativkontext.',
    'reality.input': 'Artikellink',
    'reality.placeholder': 'Füge einen Artikellink zur Analyse ein',
    'reality.open': 'Analyse öffnen',
    'reality.unavailable': 'Für diese URL ist derzeit keine Analyse verfügbar.',
    'reality.tryAnother': 'Probiere einen anderen Link aus oder öffne einen der folgenden Artikel.',
  },
  es: {
    'nav.globe': 'PANORAMA',
    'nav.markets': 'MERCADOS',
    'nav.reality': 'VERIFICADOR',
    'ticker.latest': 'Últimas noticias',
    'export.pdf': 'Exportar PDF',
    'export.country': 'País',
    'stats.conflicts': 'CONFLICTOS',
    'stats.highRisk': 'RIESGO ALTO',
    'stats.articles': 'ARTÍCULOS',
    'stats.sentiment': 'SENTIMIENTO MEDIO',
    'stats.countryImpact': 'IMPACTO EN {country}',
    'news.feed': 'Flujo de noticias',
    'news.search': 'Buscar por palabra clave',
    'news.loading': 'Cargando',
    'news.impactBadge': 'Impacto en {country}',
    'news.impactTitle': 'Impacto en {country}',
    'news.noResults': 'No hay resultados para la palabra clave indicada.',
    'news.chat': 'Analizador',
    'news.original': 'Abrir artículo original',
    'news.chatTitle': 'Chat de análisis',
    'news.selected': 'Noticia seleccionada',
    'news.summary': 'Resumen',
    'news.summaryMissing': 'Aún no hay un resumen guardado para este artículo.',
    'news.topics': 'Temas',
    'news.draft': 'Escribe tu pregunta aquí...',
    'news.analyzing': 'Estoy analizando esta noticia...',
    'news.intro': 'Pregunta lo que quieras sobre esta noticia: "{title}".',
    'conflicts.activeZones': 'Zonas de conflicto activas',
    'conflicts.hotNow': 'Qué se está calentando',
    'conflicts.window': 'Últimas 72 horas',
    'conflicts.description': 'Lista clasificada de zonas de conflicto recientes. La puntuación resume frescura e intensidad de las señales.',
    'conflicts.high': 'Grave',
    'conflicts.medium': 'Tenso',
    'conflicts.low': 'A vigilar',
    'conflicts.rising': 'En aumento',
    'conflicts.cooling': 'Disminuyendo',
    'conflicts.stable': 'Estable',
    'conflicts.score': 'Puntuación',
    'conflicts.updated': 'Actualizado',
    'conflicts.newsSignal': 'señal',
    'conflicts.articles': 'Artículos',
    'conflicts.victims': 'Víctimas',
    'conflicts.empty': 'Ahora mismo no hay suficientes señales frescas e intensas para mostrar una zona activa.',
    'reality.header': 'Verificador',
    'reality.description': 'Pega un enlace y el panel mostrará el veredicto, la calidad de las fuentes, las herramientas psicológicas y el contexto narrativo.',
    'reality.input': 'Enlace del artículo',
    'reality.placeholder': 'Pega un enlace para analizarlo',
    'reality.open': 'Abrir análisis',
    'reality.unavailable': 'Actualmente no hay análisis disponible para esta URL.',
    'reality.tryAnother': 'Prueba otro enlace o abre uno de los artículos siguientes.',
  },
  fr: {
    'nav.globe': 'VUE D’ENSEMBLE',
    'nav.markets': 'MARCHÉS',
    'nav.reality': 'VÉRIFICATEUR',
    'ticker.latest': 'Dernières actualités',
    'export.pdf': 'Exporter en PDF',
    'export.country': 'Pays',
    'stats.conflicts': 'CONFLITS',
    'stats.highRisk': 'RISQUE ÉLEVÉ',
    'stats.articles': 'ARTICLES',
    'stats.sentiment': 'SENTIMENT MOYEN',
    'stats.countryImpact': 'IMPACT {country}',
    'news.feed': 'Fil d’actualité',
    'news.search': 'Recherche par mot-clé',
    'news.loading': 'Chargement',
    'news.impactBadge': 'Impact {country}',
    'news.impactTitle': 'Impact sur {country}',
    'news.noResults': 'Aucun résultat pour ce mot-clé.',
    'news.chat': 'Analyseur',
    'news.original': 'Ouvrir l’article original',
    'news.chatTitle': 'Chat d’analyse',
    'news.selected': 'Actualité sélectionnée',
    'news.summary': 'Résumé',
    'news.summaryMissing': 'Aucun résumé enregistré pour cet article.',
    'news.topics': 'Sujets',
    'news.draft': 'Écris ta question ici...',
    'news.analyzing': 'J’analyse cette actualité...',
    'news.intro': 'Pose n’importe quelle question sur cette actualité : "{title}".',
    'conflicts.activeZones': 'Zones de conflit actives',
    'conflicts.hotNow': 'Ce qui chauffe en ce moment',
    'conflicts.window': 'Dernières 72 heures',
    'conflicts.description': 'Liste classée des zones de conflit récentes. Le score résume fraîcheur et intensité des signaux.',
    'conflicts.high': 'Grave',
    'conflicts.medium': 'Tendu',
    'conflicts.low': 'À surveiller',
    'conflicts.rising': 'En hausse',
    'conflicts.cooling': 'En baisse',
    'conflicts.stable': 'Stable',
    'conflicts.score': 'Score',
    'conflicts.updated': 'Mis à jour',
    'conflicts.newsSignal': 'signal',
    'conflicts.articles': 'Articles',
    'conflicts.victims': 'Victimes',
    'conflicts.empty': 'Il n’y a pas assez de signaux frais et forts pour afficher une zone active.',
    'reality.header': 'Vérificateur',
    'reality.description': 'Colle un lien d’article et le panneau affichera le verdict, la qualité des sources, les outils psychologiques et le contexte narratif.',
    'reality.input': 'Lien de l’article',
    'reality.placeholder': 'Colle un lien à analyser',
    'reality.open': 'Ouvrir l’analyse',
    'reality.unavailable': 'Aucune analyse n’est actuellement disponible pour cette URL.',
    'reality.tryAnother': 'Essaie un autre lien ou ouvre l’un des articles suivants.',
  },
  us: {
    'nav.globe': 'OVERVIEW',
    'nav.markets': 'MARKETS',
    'nav.reality': 'REALITY CHECK',
    'ticker.latest': 'Latest News',
    'export.pdf': 'Export PDF',
    'export.country': 'Country',
    'stats.conflicts': 'CONFLICTS',
    'stats.highRisk': 'HIGH RISK',
    'stats.articles': 'ARTICLES',
    'stats.sentiment': 'AVG. SENTIMENT',
    'stats.countryImpact': '{country} IMPACT',
    'news.feed': 'News Feed',
    'news.search': 'Search by keyword',
    'news.loading': 'Loading',
    'news.impactBadge': '{country} impact',
    'news.impactTitle': 'Impact on {country}',
    'news.noResults': 'No results for the given keyword.',
    'news.chat': 'Analyzer',
    'news.original': 'Open original article',
    'news.chatTitle': 'News Analysis Chat',
    'news.selected': 'Selected story',
    'news.summary': 'Summary',
    'news.summaryMissing': 'No saved summary is available for this article yet.',
    'news.topics': 'Topics',
    'news.draft': 'Type your question here...',
    'news.analyzing': 'Analyzing this story...',
    'news.intro': 'Ask anything about this story: "{title}".',
    'conflicts.activeZones': 'Active Conflict Zones',
    'conflicts.hotNow': 'What’s Heating Up',
    'conflicts.window': 'Last 72 hours',
    'conflicts.description': 'Ranked list of fresh conflict zones. The score compresses recency and signal strength into one number.',
    'conflicts.high': 'Severe',
    'conflicts.medium': 'Tense',
    'conflicts.low': 'Watchlist',
    'conflicts.rising': 'Rising',
    'conflicts.cooling': 'Cooling',
    'conflicts.stable': 'Stable',
    'conflicts.score': 'Score',
    'conflicts.updated': 'Updated',
    'conflicts.newsSignal': 'signal',
    'conflicts.articles': 'Articles',
    'conflicts.victims': 'Victims',
    'conflicts.empty': 'There are not enough strong fresh conflict signals to display an active zone right now.',
    'reality.header': 'Reality Check',
    'reality.description': 'Paste an article link and the panel will show the verdict, source quality, psychological tools, and narrative context.',
    'reality.input': 'Article link',
    'reality.placeholder': 'Paste an article link to analyze',
    'reality.open': 'Open analysis',
    'reality.unavailable': 'There is currently no analysis available for this URL.',
    'reality.tryAnother': 'Try another link or open one of the articles below.',
  },
  fi: {
    'nav.globe': 'YLEISKUVA',
    'nav.markets': 'MARKKINAT',
    'nav.reality': 'TARKISTUS',
    'ticker.latest': 'Tuoreimmat uutiset',
    'export.pdf': 'Vie PDF',
    'export.country': 'Maa',
    'stats.conflicts': 'KONFLIKTIT',
    'stats.highRisk': 'KORKEA RISKI',
    'stats.articles': 'ARTIKKELIT',
    'stats.sentiment': 'KESKIM. TUNNELMA',
    'stats.countryImpact': '{country}-VAIKUTUS',
    'news.feed': 'Uutisvirta',
    'news.search': 'Hae avainsanalla',
    'news.loading': 'Ladataan',
    'news.impactBadge': '{country}-vaikutus',
    'news.impactTitle': 'Vaikutus maahan {country}',
    'news.noResults': 'Hakusanalla ei löytynyt tuloksia.',
    'news.chat': 'Analyysi',
    'news.original': 'Avaa alkuperäinen artikkeli',
    'news.chatTitle': 'Uutisanalyysichat',
    'news.selected': 'Valittu uutinen',
    'news.summary': 'Yhteenveto',
    'news.summaryMissing': 'Tälle artikkelille ei ole vielä tallennettua yhteenvetoa.',
    'news.topics': 'Aiheet',
    'news.draft': 'Kirjoita kysymyksesi tähän...',
    'news.analyzing': 'Analysoin tätä uutista...',
    'news.intro': 'Kysy mitä tahansa tästä uutisesta: "{title}".',
    'conflicts.activeZones': 'Aktiiviset konfliktialueet',
    'conflicts.hotNow': 'Mikä kuumenee nyt',
    'conflicts.window': 'Viimeiset 72 tuntia',
    'conflicts.description': 'Tuoreiden konfliktialueiden järjestetty lista. Pisteytys yhdistää tuoreuden ja signaalien voimakkuuden.',
    'conflicts.high': 'Vakava',
    'conflicts.medium': 'Jännittynyt',
    'conflicts.low': 'Seurattava',
    'conflicts.rising': 'Kasvaa',
    'conflicts.cooling': 'Laimenee',
    'conflicts.stable': 'Vakaa',
    'conflicts.score': 'Pisteet',
    'conflicts.updated': 'Päivitetty',
    'conflicts.newsSignal': 'signaali',
    'conflicts.articles': 'Artikkelit',
    'conflicts.victims': 'Uhrit',
    'conflicts.empty': 'Juuri nyt ei ole tarpeeksi vahvoja tuoreita signaaleja aktiivisen alueen näyttämiseen.',
    'reality.header': 'Todellisuustarkistus',
    'reality.description': 'Liitä artikkelilinkki, niin paneeli näyttää tuomion, lähteiden laadun, psykologiset keinot ja narratiivisen kontekstin.',
    'reality.input': 'Artikkelilinkki',
    'reality.placeholder': 'Liitä analysoitava artikkelilinkki',
    'reality.open': 'Avaa analyysi',
    'reality.unavailable': 'Tälle URL-osoitteelle ei ole juuri nyt analyysiä saatavilla.',
    'reality.tryAnother': 'Kokeile toista linkkiä tai avaa jokin alla olevista artikkeleista.',
  },
  nl: {
    'nav.globe': 'OVERZICHT',
    'nav.markets': 'MARKTEN',
    'nav.reality': 'REALITEITSCHECK',
    'ticker.latest': 'Laatste nieuws',
    'export.pdf': 'PDF exporteren',
    'export.country': 'Land',
    'stats.conflicts': 'CONFLICTEN',
    'stats.highRisk': 'HOOG RISICO',
    'stats.articles': 'ARTIKELEN',
    'stats.sentiment': 'GEM. SENTIMENT',
    'stats.countryImpact': '{country}-IMPACT',
    'news.feed': 'Nieuwsfeed',
    'news.search': 'Zoek op trefwoord',
    'news.loading': 'Laden',
    'news.impactBadge': '{country}-impact',
    'news.impactTitle': 'Impact op {country}',
    'news.noResults': 'Geen resultaten voor dit zoekwoord.',
    'news.chat': 'Analist',
    'news.original': 'Open origineel artikel',
    'news.chatTitle': 'Nieuwsanalyse-chat',
    'news.selected': 'Geselecteerd bericht',
    'news.summary': 'Samenvatting',
    'news.summaryMissing': 'Er is nog geen opgeslagen samenvatting voor dit artikel.',
    'news.topics': 'Onderwerpen',
    'news.draft': 'Typ hier je vraag...',
    'news.analyzing': 'Ik analyseer dit bericht...',
    'news.intro': 'Vraag alles over dit bericht: "{title}".',
    'conflicts.activeZones': 'Actieve conflictzones',
    'conflicts.hotNow': 'Wat nu oplaait',
    'conflicts.window': 'Laatste 72 uur',
    'conflicts.description': 'Gerangschikte lijst van recente conflictzones. De score vat actualiteit en signaalsterkte samen.',
    'conflicts.high': 'Ernstig',
    'conflicts.medium': 'Gespannt',
    'conflicts.low': 'Volgen',
    'conflicts.rising': 'Stijgend',
    'conflicts.cooling': 'Afnemend',
    'conflicts.stable': 'Stabiel',
    'conflicts.score': 'Score',
    'conflicts.updated': 'Bijgewerkt',
    'conflicts.newsSignal': 'signaal',
    'conflicts.articles': 'Artikelen',
    'conflicts.victims': 'Slachtoffers',
    'conflicts.empty': 'Er zijn nu niet genoeg sterke, recente signalen om een actieve zone te tonen.',
    'reality.header': 'Realiteitscheck',
    'reality.description': 'Plak een artikellink en het paneel toont het oordeel, de bronkwaliteit, psychologische technieken en narratieve context.',
    'reality.input': 'Artikellink',
    'reality.placeholder': 'Plak een link om te analyseren',
    'reality.open': 'Analyse openen',
    'reality.unavailable': 'Voor deze URL is momenteel geen analyse beschikbaar.',
    'reality.tryAnother': 'Probeer een andere link of open een van de onderstaande artikelen.',
  },
} as const;

interface CountryContextValue {
  country: CountryConfig;
  countryCode: CountryCode;
  setCountryCode: (code: CountryCode) => void;
  t: (key: string, vars?: Record<string, string>) => string;
  formatDate: (value: number | string | Date, options?: Intl.DateTimeFormatOptions) => string;
  themeStyle: Record<string, string>;
}

const CountryContext = createContext<CountryContextValue | null>(null);

function interpolate(template: string, vars?: Record<string, string>) {
  if (!vars) return template;
  return Object.entries(vars).reduce(
    (output, [key, value]) => output.replaceAll(`{${key}}`, value),
    template,
  );
}

export function adaptCountryReference(text: string, countryName: string) {
  return text
    .replace(/\bHungary\b/g, countryName)
    .replace(/\bMagyarország\b/g, countryName)
    .replace(/\bHungarian\b/g, countryName);
}

export function replaceWithMap(text: string, replacements: Record<string, string>) {
  return Object.entries(replacements).reduce(
    (output, [source, target]) => output.replaceAll(source, target),
    text,
  );
}

export function CountryProvider({ children }: { children: ReactNode }) {
  const [countryCode, setCountryCode] = useState<CountryCode>('hu');
  const country = COUNTRY_CONFIGS[countryCode];

  const value = useMemo<CountryContextValue>(() => ({
    country,
    countryCode,
    setCountryCode,
    t: (key, vars) => {
      const table = UI_TRANSLATIONS[countryCode] ?? UI_TRANSLATIONS.hu;
      const template = table[key as keyof typeof table] ?? UI_TRANSLATIONS.hu[key as keyof typeof UI_TRANSLATIONS.hu] ?? key;
      return interpolate(template, vars);
    },
    formatDate: (value, options) => new Intl.DateTimeFormat(country.locale, options).format(new Date(value)),
    themeStyle: {
      '--country-accent': country.accentHex,
      '--country-accent-hover': country.accentHoverHex,
      '--country-accent-rgb': country.accentRgb,
      '--accent': country.accentHsl,
      '--destructive': country.accentHsl,
      '--ring': country.accentHsl,
      '--border': country.borderHsl,
      '--input': country.inputHsl,
      '--sidebar-primary': country.accentHsl,
      '--sidebar-ring': country.accentHsl,
    },
  }), [country, countryCode]);

  return <CountryContext.Provider value={value}>{children}</CountryContext.Provider>;
}

export function useCountry() {
  const context = useContext(CountryContext);
  if (!context) {
    throw new Error('useCountry must be used within CountryProvider');
  }
  return context;
}

export const COUNTRY_OPTIONS = Object.values(COUNTRY_CONFIGS);
